import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>어서와</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <iframe
          width="560"
          height="615"
          src="https://www.youtube.com/embed/5pRIDXQJxzw"
          title="YouTube video player"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        ></iframe>
        <h1 className={styles.title}></h1>
        <div className={styles.grid}>너가 생각하는 모든것들을만들어봐</div>
      </main>
    </div>
  );
};

export default Home;
